[toolchain]
channel = "1.91.0"
profile = "default"
components = ["rustfmt", "clippy", "rust-analyzer"]
targets = [
    "aarch64-apple-ios-sim",
    "aarch64-apple-ios",
    "x86_64-apple-ios",
    "x86_64-unknown-linux-gnu",
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "x86_64-linux-android",
    "i686-linux-android",
]
